### ISSUE TITLE
pychrono 5.0.0 API change

### ISSUE THREAD

**Issue by davidbrochart** [erdc/proteus#1101]
It looks like pychrono 5.0.0 has some backward-incompatible API changes, like `chrono/solver/ChSolverMINRES.h` which has been renamed `chrono/solver/ChSolverPMINRES.h` (and the corresponding C++ objects). For this particular example, these files have to be updated:
- `proteus/mbd/ProtChMoorings.h`
- `proteus/mbd/ProtChBody.h`

A compilation log can be found in the proteus conda-forge recipe (https://github.com/conda-forge/proteus-feedstock/pull/20):
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=125079&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c

**Comment by tridelat** [comment]
@davidbrochart are we switching to 5.0.0 now? I think it's a good idea to upgrade in any case, just wondering if there is a particular feature from 5.0.0 that we would like to have right away.
I will look at those compatibility issues on the mbd files

**Comment by davidbrochart** [comment]
> @davidbrochart are we switching to 5.0.0 now?

I don't know, it's really up to you. The thing is that I got pychrono to compile in conda-forge on OSX for v5.0.0, but I didn't try with v4.0.0. I thought we agreed to wait for v5.0.0 to enable OSX, but if it's needed right now we could try and have a v4.0.0 on OSX too.

**Comment by tridelat** [comment]
> > @davidbrochart are we switching to 5.0.0 now?
> 
> I don't know, it's really up to you. The thing is that I got pychrono to compile in conda-forge on OSX for v5.0.0, but I didn't try with v4.0.0. I thought we agreed to wait for v5.0.0 to enable OSX, but if it's needed right now we could try and have a v4.0.0 on OSX too.

Some classes changed in 5.0.0, making some members private when they were accessible before. This makes it difficult for derived Chrono classes defined in proteus/mbd that need to use those private members, so I am not sure that it will be an easy switch, see PR #1102

**Comment by davidbrochart** [comment]
pychrono v4.0.0 now compiles on OSX too (https://github.com/conda-forge/pychrono-feedstock/pull/8), so no worries if proteus can't switch to v5.0.0 right now.

**Comment by cekees** [comment]
> > > @davidbrochart are we switching to 5.0.0 now?
> > 
> > 
> > I don't know, it's really up to you. The thing is that I got pychrono to compile in conda-forge on OSX for v5.0.0, but I didn't try with v4.0.0. I thought we agreed to wait for v5.0.0 to enable OSX, but if it's needed right now we could try and have a v4.0.0 on OSX too.
> 
> Some classes changed in 5.0.0, making some members private when they were accessible before. This makes it difficult for derived Chrono classes defined in proteus/mbd that need to use those private members, so I am not sure that it will be an easy switch, see PR #1102

@tridelat there are probably several ways around this in the short run. On the hashdist side you can just patch the chrono source with the data made public again or maybe more correctly add member functions or friend declarations to recover access to what you need. I'm guessing conda has a patch capability as well. It's a bit surprising that the chrono changes don't provide a way to get/set the data you need to modify after switching the data to private.

**Comment by tridelat** [comment]
> > > > @davidbrochart are we switching to 5.0.0 now?
> > > 
> > > 
> > > I don't know, it's really up to you. The thing is that I got pychrono to compile in conda-forge on OSX for v5.0.0, but I didn't try with v4.0.0. I thought we agreed to wait for v5.0.0 to enable OSX, but if it's needed right now we could try and have a v4.0.0 on OSX too.
> > 
> > 
> > Some classes changed in 5.0.0, making some members private when they were accessible before. This makes it difficult for derived Chrono classes defined in proteus/mbd that need to use those private members, so I am not sure that it will be an easy switch, see PR #1102
> 
> @tridelat there are probably several ways around this in the short run. On the hashdist side you can just patch the chrono source with the data made public again or maybe more correctly add member functions or friend declarations to recover access to what you need. I'm guessing conda has a patch capability as well. It's a bit surprising that the chrono changes don't provide a way to get/set the data you need to modify after switching the data to private.

@cekees I decided to redeclare the private variables, so it "hides" the parent private variable. Hopefully this won't create issues.
Now I run in compilation problems with cython with an error at a higher level (setup.py) with limited information about the error. To compile, I use the stack from https://github.com/erdc/stack/pull/48

**Comment by tridelat** [comment]
@cekees I am also surprised that some of those variables were made private (not sure what was the reason for this). Even though a typical user of Chrono would not need to access them, it makes it rather inconvenient to derive child classes. Protected attribute might have been sufficient

**Comment by tridelat** [comment]
The compilation error:
```
    cythoning proteus/mbd/CouplingFSI.pyx to proteus/mbd/CouplingFSI.cpp
    /home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: proteus/mbd/CouplingFSI.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
    warning: proteus/mbd/CouplingFSI.pyx:356:15: local variable 'ang' referenced before assignment
    warning: proteus/mbd/CouplingFSI.pyx:2405:36: Index should be typed for more efficient access
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/tridelat/PROTEUS/proteus/setup.py", line 935, in <module>
        setup_extensions_in_sequential()
      File "/home/tridelat/PROTEUS/proteus/setup.py", line 919, in setup_extensions_in_sequential
        setup_given_extensions(EXTENSIONS_TO_BUILD)
      File "/home/tridelat/PROTEUS/proteus/setup.py", line 915, in setup_given_extensions
        requires=['numpy']
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
        ext.sources = self.cython_sources(ext.sources, ext)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
        full_module_name=module_name)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 776, in compile
        return compile_single(source, options, full_module_name)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 725, in compile_single
        return run_pipeline(source, options, full_module_name)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 513, in run_pipeline
        err, enddata = Pipeline.run_pipeline(pipeline, source)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
        data = run(phase, data)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
        return phase(data)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
        module_node.process_implementation(options, result)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/ModuleNode.py", line 143, in process_implementation
        self.generate_c_code(env, options, result)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/ModuleNode.py", line 384, in generate_c_code
        self.body.generate_function_definitions(env, code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_function_definitions
        stat.generate_function_definitions(env, code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_function_definitions
        stat.generate_function_definitions(env, code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 4839, in generate_function_definitions
        self.body.generate_function_definitions(self.scope, code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_function_definitions
        stat.generate_function_definitions(env, code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 3173, in generate_function_definitions
        FuncDefNode.generate_function_definitions(self, env, code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 1983, in generate_function_definitions
        self.generate_function_body(env, code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 1745, in generate_function_body
        self.body.generate_execution_code(code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 448, in generate_execution_code
        stat.generate_execution_code(code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6253, in generate_execution_code
        if_clause.generate_execution_code(code, end_label, is_last=i == last)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6315, in generate_execution_code
        self.body.generate_execution_code(code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 448, in generate_execution_code
        stat.generate_execution_code(code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6909, in generate_execution_code
        self.body.generate_execution_code(code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 448, in generate_execution_code
        stat.generate_execution_code(code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6909, in generate_execution_code
        self.body.generate_execution_code(code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 448, in generate_execution_code
        stat.generate_execution_code(code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6253, in generate_execution_code
        if_clause.generate_execution_code(code, end_label, is_last=i == last)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6315, in generate_execution_code
        self.body.generate_execution_code(code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 448, in generate_execution_code
        stat.generate_execution_code(code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 5168, in generate_execution_code
        self.generate_rhs_evaluation_code(code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 5455, in generate_rhs_evaluation_code
        self.rhs.generate_evaluation_code(code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/ExprNodes.py", line 771, in generate_evaluation_code
        self.generate_result_code(code)
      File "/home/tridelat/PROTEUS/proteus/linux/lib/python3.7/site-packages/Cython/Compiler/ExprNodes.py", line 13207, in generate_result_code
        self.arg.type.to_py_call_code(
    AttributeError: 'ErrorType' object has no attribute 'to_py_call_code'
```

**Comment by tridelat** [comment]
@cekees @davidbrochart just an update: got past this error, it seems that it was because of trying to use the operator() on a variable without declaring it. In any case, it compiles with chrono 5.0.0 now on #1102

**Comment by davidbrochart** [comment]
Awesome @tridelat, should we make a minor release of proteus, so that I can update the conda-forge feedstock?

**Comment by tridelat** [comment]
@davidbrochart yes we can do a minor release if it helps for the conda side, we just need to make sure that the switch to 5.0.0 does not introduce bugs first

**Comment by davidbrochart** [comment]
I tried to build proteus in conda-forge on OSX using chrono v4.0.0, but I get a strange error (`Symbol not found: _dcopy_`):
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=125290&view=logs&j=ce7cbaa7-582c-5570-40f4-267b3d85fc9f&t=4a56039b-7269-50ae-de7a-538e91e6de06&l=49124

**Comment by tridelat** [comment]
@davidbrochart not sure about this error on OSX.
I get errors on the the tests of the conda dev install of PR https://github.com/erdc/proteus/pull/1103 which should not affect any part of the code. I forced chrono =4.0.0 in environment-dev.yml (because it defaults to 5.0.0 otherwise), but maybe some other packages were updated to a new version and cause the errors?
The errors are due to small mismatch of numerical results

**Comment by tridelat** [comment]
@davidbrochart as an update, I the relevant tests to pass with chrono 5.0.0 on #1102, but the conda install is failing some other tests that are not affected by the changes and that used to pass.
I am suspecting that some packages that do not have an explicit version number in `environment-dev.yml` have been updated on the conda side and now give slightly different numerical values on some tests, but I am not sure if there is an easy way to check what package could cause this problem.

We might want to give version numbers to packages when we can so that we don't get unexpected behaviour for the tests. Or we need to fix tests so they are less sensitive. The tests pass on hashdist on #1103.

@cekees @zhang-alvin

**Comment by davidbrochart** [comment]
Yes maybe it is due to small numerical differences caused by changes in newer versions of the dependencies. We could pin those dependencies, but that's not good if we want to make proteus install easily in more complex environments. Also, if one day we have to update a dependency, the tests have to be updated anyway.
I agree that this is more work for you, but the best would be indeed to have less sensitive tests, e.g. use `numpy.isclose` instead of strict equality where this is applicable.
That being said, do you want me to pin the packages to the versions that were passing the tests, just to make sure that it is the issue?

**Comment by tridelat** [comment]
@davidbrochart yes I agree, it is better to update the tests rather than pinning dependencies if it makes the install easier on more complex environments. 
We already use `np.isclose`, `np.allclose`, and `np.assert_almost_equal` in those tests, but some of them need to be even more loose.

**Comment by tridelat** [comment]
Some of those tests seem to have quite a non-negligible variation, e.g.:
```
[gw0] linux -- Python 3.8.2 /home/tridelat/miniconda3/envs/proteus-dev/bin/python
self = <proteus.tests.post_processing.test_bdm2_3d_mesh.TestBDM2Mesh3D object at 0x7f4718558be0>

    def test_BDM2_reference_triangle_full_in_space(self):
        rel_path_1 = "import_modules/bdm_bdy_func_values_3dmesh.data"
        rel_path_2 = "import_modules/bdm_func_values_3dmesh.data"
        bdm_bdy_values = np.load(os.path.join(self.scriptdir,rel_path_1))
        bdm_values = np.load(os.path.join(self.scriptdir,rel_path_2))
    
        self.bdm2_obj.ebq[('velocity',0)] = bdm_bdy_values.copy()
        self.bdm2_obj.q[('velocity',0)] = bdm_values.copy()
    
        self.bdm2_obj.evaluateLocalVelocityRepresentation(0,True)
>       np.testing.assert_almost_equal(self.bdm2_obj.q[('velocity',0)],bdm_values,decimal=6)
E       AssertionError: 
E       Arrays are not almost equal to 6 decimals
E       
E       (mismatch 93.65079365079364%)
E        x: array([[[-3.187041e-01, -4.376730e-01,  3.418274e-02],
E               [-1.541336e+00, -1.541336e+00, -1.427859e+00],
E               [-2.834572e-01, -3.324521e-01,  4.323069e-01],...
E        y: array([[[ 0.      , -0.75    ,  0.      ],
E               [-1.      , -1.      ,  0.      ],
E               [-0.25    , -0.25    ,  0.      ],...

proteus/tests/post_processing/test_bdm2_3d_mesh.py:72: AssertionError
```
So there might be more than just slight numerical differences, as they pass on the hashdist install

**Comment by zhang-alvin** [comment]
There might be merit in switching these solves to using direct solvers if they are not already. The sensitivity in the numerics might be coming from when I switched it over to a constant mesh approach, but the mesh being rather coarse.

**Comment by tridelat** [comment]
@davidbrochart if you have an easy way to find the package versions that were used and passing the tests before, it would be useful to pin it. It might actually be better for now to have dependencies fixed to specific versions so we are sure that the build is fit for our applications, and to update dependencies on a case-by-case basis when necessary (and deal with failing tests accordingly)

**Comment by davidbrochart** [comment]
Sure, I will look at it.
